feat: focus animation for slideshow
quochung-cyou/GGStudy pull request #160
Opened 2024-09-12 13:11 UTC by NguyenBui256

2024-09-12 14:45 UTC, quochung-cyou requested changes

2024-09-12 14:45 UTC, quochung-cyou commented on backend/src/main/java/web/controller/ProjectController.java
> +    public CustomResponse<Project> createProjectsFromOutlines(@RequestParam String topicName, @RequestBody List<Outline> outlines) throws IOException {
cái này lại xoá mất luồng tạo mới của Minh này

2024-09-12 14:50 UTC, NguyenBui256 commented on backend/src/main/java/web/controller/ProjectController.java
> +    public CustomResponse<Project> createProjectsFromOutlines(@RequestParam String topicName, @RequestBody List<Outline> outlines) throws IOException {
em thêm cái title cho project vào cái cũ của Minh thôi ạ

2024-09-12 16:15 UTC, quochung-cyou requested changes

2024-09-12 20:32 UTC, NguyenBui256 commented on backend/src/main/java/web/common/dto/SlideInputFormat.java
> +    private List<AnimationInputFormat> animations;
em check khác null trước khi dùng phần tử r ạ

2024-09-13 03:47 UTC, quochung-cyou approved these changes

2024-09-13 08:58 UTC, merged